"""
Robert Graham (rpgraham84@gmail.com)
Project Euler

Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:
4613732

"""


def fib(x=0, y=1):
    while y <= 4_000_000:
        x, y = y, x + y
        if not y % 2:
            yield y


def problem_2():
    return sum(fib())


if __name__ == "__main__":
    print(problem_2())